export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SEARCH_CANDIDATES = 'SEARCH_CANDIDATES';
export const SAVE_CANDIDATE = 'SAVE_CANDIDATE';
